from __future__ import annotations

from typing import Any, Protocol


class VectorPoint(Protocol):
    id: str
    vector: list[float]
    sparse: list[Any] | None
    payload: dict


class VectorStore(Protocol):
    async def ensure_collection(self, *, name: str, dim: int, sparse: bool = False) -> None: ...
    async def upsert(self, *, collection: str, points: list[Any]) -> None: ...
    async def delete(self, *, collection: str, ids: list[str]) -> None: ...
    async def delete_by_filter(self, *, collection: str, must: list[dict]) -> None: ...
    async def search_dense(self, *, collection: str, vector: list[float], filters: dict, limit: int) -> list[dict]: ...
    async def search_sparse(self, *, collection: str, indices: list[int], values: list[float], filters: dict, limit: int) -> list[dict]: ...
    async def count(self, *, collection: str, filters: dict | None = None) -> int: ...
    async def collection_exists(self, *, name: str) -> bool: ...
    async def delete_collection(self, *, name: str) -> None: ...
